### ISSUE TITLE
Instructions for getting ID unclear

### ISSUE THREAD

**Issue by chut** [Leverege/microchip-avr-iot#2]
I scanned the QR code and it gave an ID similar to what I found in KIT_INFO.TXT as serial.

However, my device ID in the console used before configuring my own project is completely different.

I have not yet gotten this working with my device, but guess this may be the reason. What ID is supposed to be used?

**Comment by Yitaek** [comment]
The serial number you see when you scan the QR code (https://avr-iot.com/device/<serial #/deviceId>) and what populates in the KIT_INFO.TXT should be the same. The device ID used in IoT Core registry is prefixed by "d" (d<serial #/device ID>) due to the constraint that IDs must start with letters on IoT Core. 

I am a bit surprised to hear that the device ID in the console is completely different than the serial # you see in KIT_INFO.TXT (I'm wondering if that variable is being set elsewhere). In either case, we'll update the instructions to clarify what we mean by device ID!

**Comment by chut** [comment]
I can post the different ID numbers that I see in different places if that helps.

However, I am still having the same problem. The device works fine when originally configured but when I follow the steps to "graduate" and add it to my own registry, I never see any data. Are you sure these are the only steps I have to follow? Don't need to do anything on the device itself?

**Comment by kevinnilson** [comment]
I have the same experience.  I haven't been able to get device data from my
own registry.

**Comment by mattgif** [comment]
The script is looking for the UID string in the url you get from launching CLICK-ME.HTM on the device: http://avr-iot.com/device/<UID>

I'm updating the instructions to reflect this.

**Comment by mattgif** [comment]
Instructions updated.
